version: 2.1
jobs:
  build:
    docker:
      - image: cyversevice/shiny-neon-browser:3.6.3
    steps:
      - run:
          name: Check4R
          command: |
            echo 'Check if R is installed'
            R --version
