version: 2.1
jobs:
  build:
    docker:
      - image: cyversevice/shiny-neon-browser:3.6.3
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  check:
    docker:
      - image: cyversevice/shiny-neon-browser:3.6.3
    steps:
      - checkout
      - run:
          name: R ver
          command: |
            R --version 
